### ISSUE TITLE
Test tools

### ISSUE THREAD

**Issue by 0xB10C** [0xB10C/peer-observer#26]
By recording and then replaying some of the nanomsg/protobuf communication that the extractor publishes, we can write regression test for the tools in the CI. This would be useful to have!

See also: https://github.com/0xB10C/peer-observer/pull/25#issuecomment-2246349226

**Comment by 0xB10C** [comment]
An alternative to a NATS JetStream based approach could be a testing-extractor that publishes a fixed set of messages into a NATS server and clients read from it. This might be easier to implement and makes it easier to add new test cases since we don't need to recreate a NATS JetStream file to read from. A workflow for this would be similar to:

- Spin up a NATS server in GH Actions (using Docker or binary).
- Wait until NATS is ready.
- Run a tool / consumer.
- Run the testing-extractor / publisher (it should send a few test messages).
- Assert/test that the tool output is as expected

A GH actions workflow to run a NATS server could look similar to:

```yaml
name: Integration Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      nats:
        image: nats:latest
        ports:
          - 4222:4222
        options: >-
          --health-cmd "nats-server -v"
          --health-interval 5s
          --health-timeout 10s
          --health-retries 5

    steps:
...
```
